version: '3.8'

services:
  mkdocs:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./docs:/docs
    stdin_open: true
    tty: true
    command: serve --dev-addr=0.0.0.0:8000
