name: Execute Fixed Commands on EC2 via SSM

on:
  workflow_dispatch: # 手動でワークフローを実行可能にする
  # push: # 特定のブランチへのpush時に実行する場合
  #   branches:
  #     - main

jobs:
  execute-fixed-ssm-command:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # AWS OIDC認証に必要
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Send SSM Command with Fixed Script
        env:
          # GitHub Secretsの値を環境変数として設定
          # これにより、aws ssm send-command の --parameters でシェルスクリプトに変数を渡せる
          MY_SECRET_VALUE_ON_EC2: ${{ secrets.MY_SECRET_VALUE }}
        run: |
          echo "Sending commands to instance: ${{ secrets.EC2_INSTANCE_ID }}"

          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --parameters commands='cat "${{ secrets.MY_SECRET_VALUE }}" > /tmp/actions.log' \
            --comment "GitHub Actions: Execute Fixed Script" \
            --query "Command.CommandId" \
            --output text)

          if [ -z "$COMMAND_ID" ]; then
            echo "Failed to send command"
            exit 1
          fi

          echo "SSM Command ID: $COMMAND_ID"
          echo "Waiting for command to complete..."
          aws ssm wait command-executed --command-id "$COMMAND_ID" --instance-id "${{ secrets.EC2_INSTANCE_ID }}"

          echo "Command execution completed. Fetching output..."
          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id "${{ secrets.EC2_INSTANCE_ID }}" \
            --query "{StandardOutputContent:StandardOutputContent, StandardErrorContent:StandardErrorContent, Status:Status}" \
            --output json
